spring.application.name=SpringSecurityApp


#DataBase configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/securitydb
spring.datasource.username=root
#spring.datasource.password=secret


#Security Config

#spring.security.user.name=ignacio
#spring.security.user.password=1234
